The ``7-base_geometry`` module
======================

Using ``BaseGeometry``
-------------------

    >>> BaseGeometry = __import__('7-base_geometry').BaseGeometry
    >>> bg = BaseGeometry()

     >>> bg = BaseGeometry()
    >>> bg.area()
    Traceback (most recent call last):
    	      ...
    Exception: area() is not implemented

    >>> bg.area(324)
    Traceback (most recent call last):
    	      ...
    Exception: area() takes 1 positional argument but 2 were give

    >>> bg.integer_validator("dob", 123)

    >>> bg = BaseGeometry()

    >>> bg.integer_validator("dob", 1)

    >>> bg = BaseGeometry()

    >>> bg.integer_validator("dob", -10)
    Traceback (most recent call last):
        ...
    ValueError: dob must be greater than 0

    >>> bg = BaseGeometry()

    >>> bg.integer_validator("dob", 0)
    Traceback (most recent call last):
        ...
    ValueError: dob must be greater than 0

    >>> bg = BaseGeometry()
    >>> bg.integer_validator("dob", 10.0)
    Traceback (most recent call last):
        ...
    TypeError: dob must be an integer

    >>> bg = BaseGeometry()

    >>> bg.integer_validator("dob", "10")
    Traceback (most recent call last):
        ...
    TypeError: dob must be an integer

    >>> bg = BaseGeometry()

    >>> bg.integer_validator("dob", [10])
    Traceback (most recent call last):
        ...
    TypeError: dob must be an integer

    >>> bg = BaseGeometry()

    >>> bg.integer_validator("dob", (10, ))
    Traceback (most recent call last):
        ...
    TypeError: dob must be an integer

    >>> bg = BaseGeometry()

    >>> bg.integer_validator("dob")
    Traceback (most recent call last):
        ...
    TypeError: integer_validator() missing 1 required positional argument: 'value'

    >>> bg = BaseGeometry()

    >>> bg.integer_validator()
    Traceback (most recent call last):
        ...
    TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

    >>> bg = BaseGeometry()

    >>> bg.integer_validator("name", 10, 25)
    Traceback (most recent call last):
    	...
    TypeError: integer_validator() takes 3 positional arguments but 4 were given